[package]
name = "scheme-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.0.0"
radix_fmt = "1"
itertools = "0.10"
macros = { path = "macros" }
wasm-bindgen = "0.2.78"
uuid = { version = "1.1.2", features = [ "v4", "fast-rng", "js" ] }
num = "0.4.0"