;; TODO - Import test function
(define (test a b) (eq? a b))


(test (atom? 'atom) #t)
(test (atom? 'turkey) #t)
(test (atom? 1729) #t)
(test (atom? 'u) #t)
(test (atom? '*abc$) #t)
(test (atom? #\a) #t)
(test (atom? '(Harry had a heap of apples)) #f)
(test (atom? (car '(Harry had a heap of apples))) #t)
(test (atom? (cdr '(Harry had a heap of apples))) #f)
(test (atom? (car (cdr '(swing low sweet cherry oat)))) #t)
(test (atom? (car (cdr '(swing (low sweet) cherry oat)))) #f)
(test (atom? (cdr '(Harry))) #f)
(test (list? '(atom)) #t)
(test (list? '(atom turkey or)) #t)
(test (list? '((atom turkey) or)) #t)
(test (list? '()) #t)
(test (atom? '()) #f)
(test (list? '(() () () ())) #t)
(test (list? '(1 . 2)) #f)
(test (list? '(1 . (2))) #t)
(test (list? '(1 . ())) #t)

(test (car '(a b c)) 'a)
(test (car '((a b c) x y z)) '(a b c))
(test (car '(((hotdogs)) (and) (pickle) relish)) '((hotdogs)))
(test (car (car '(((hotdogs)) (and) (pickle) relish))) '(hotdogs))
(test (cdr '(a b c)) '(b c))
(test (cdr '((a b c) x y z)) '(x y z))
(test (cdr '(hamburger)) '())
(test (cdr '((x) t r)) '(t r))
(test (car (cdr '((b) (x y) ((e))))) '(x y))
(test (cdr (cdr '((b) (x y) ((e))))) '(((e))))

(test (cons 'peanut '(butter and jelly)) '(peanut butter and jelly))
(test (cons '(banana and) '(peanut butter and jelly)) '((banana and) peanut butter and jelly))
(test (cons '((help) this) '(is very ((hard) to learn))) '(((help) this) is very ((hard) to learn)))
(test (cons '(a b (c)) '()) '((a b (c))))
(test (cons 'a '()) '(a))
(test (cons 'a (car '((b) c d))) '(a b))
(test (cons 'a (cdr '((b) c d))) '(a c d))

(test (null? '()) #t)
(test (null? (quote ())) #t)
(test (null? '(a b c)) #f)

(test (eq? 'Harry 'Harry) #t)
(test (eq? 'butter 'margarine) #f)
(test (eq? (car '(Mary had a little lamb chop)) 'Mary) #t)
(test (eq? (car '(beans beans we need jelly beans)) (car (cdr '(beans beans we need jelly beans)))) #t)

;;
'OK